# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOe3FXtv8iVYsnj6fXDsmMmLoOh0MuMp
"""

import requests, json 
  
# enter your api key here 
api_key = 'YOUR_API_KEY'

def getLongLatFromLocation(currentlat, currentlong, radius, destination, keyword):
  url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
  response = requests.get(url + 'location=' + currentlat+','+currentlong +'&key=' + api_key +'&radius='+ radius+ '&type='+destination+'&keyword='+keyword)
  rjson = response.json()
  return rjson['results']

results = getLongLatFromLocation('-33.8670522','151.1957362','1500','restaurant', '')

results